---
schema_version: 1

default_environment: staging

artifacts:
  django:
    build_steps:
      - type: docker_image
        spec_type: Dockerfile
        image_name: gcr.io/covalent-project/auto-spf-flattener
        source_path: "."
